### ISSUE TITLE
How to adapt to high speed moving object ?

### ISSUE THREAD

**Issue by wwdok** [prasadkevin/Object_tracking_sort#1]
Hi, @prasadkevin , thank you sharing this repo, in my case, i replace the detector model with [MobileNetSSD_deploy.prototxt](https://github.com/chuanqi305/MobileNet-SSD/blob/master/voc/MobileNetSSD_deploy.prototxt) and [MobileNetSSD_deploy.caffemodel](https://github.com/Ghustwb/MobileNet-SSD-TensorRT/blob/master/model/MobileNetSSD_deploy.caffemodel), and this is the video i tested: [video2](https://streamja.com/A0EAn),
the output video is [here](https://streamja.com/oP5J5). As you can see, the tracking result is not so good, so how to modify the code to make it adapt to such situation ? Thanks !

**Comment by wwdok** [comment]
Now i know， just set `frame_skip` to be small is ok !

**Comment by prasadkevin** [comment]
hai, @wwdok  that's cool. keep experimenting on it . its relatively useful. you can go through this repo for more details . https://github.com/ZidanMusk/experimenting-with-sort

**Comment by wwdok** [comment]
> hai, @wwdok that's cool. keep experimenting on it . its relatively useful. you can go through this repo for more details . https://github.com/ZidanMusk/experimenting-with-sort

You are so nice ！It is a good repo to study too, starred it ~
